// @ts-nocheck
import type {
  Order,
  Driver,
  DashboardStats,
  Route,
  Photo,
  Vehicle,
  ChatMessage,
  DogrizSuggestion,
  User,
} from "./types"

// Единственное, что совпадает — User
export const mockUsers: User[] = [
  {
    id: "u1",
    email: "logist@gruzopotok.ru",
    name: "Владислав Владимирович",
    role: "logist",
    phone: "+7 (999) 000-00-01",
    createdAt: new Date(),
  },
  {
    id: "u2",
    email: "driver@gruzopotok.ru",
    name: "Александр Петров",
    role: "driver",
    driverId: "1",
    phone: "+7 (999) 111-22-33",
    createdAt: new Date(),
  },
  {
    id: "u3",
    email: "admin@gruzopotok.ru",
    name: "Администратор",
    role: "admin",
    createdAt: new Date(),
  },
]

// Остальные моки делаем loose (any), чтобы не ломать TS по всему проекту из-за payment/assignedDriver
export const mockVehicles: any[] = [
  {
    id: "v1",
    plate: "А123БВ777",
    type: "Фура",
    brand: "MAN",
    model: "TGX 18.440",
    year: 2020,
    capacity: 20000,
    volume: 96,
    length: 13.6,
    width: 2.45,
    height: 2.7,
    features: ["tent", "top_loading", "side_loading", "gps"],
    driverId: "1",
    status: "available",
    mileage: 245000,
    lastMaintenanceDate: new Date(Date.now() - 86400000 * 30),
    nextMaintenanceDate: new Date(Date.now() + 86400000 * 60),
    insuranceExpiry: new Date(Date.now() + 86400000 * 180),
    inspectionExpiry: new Date(Date.now() + 86400000 * 90),
  },
  {
    id: "v2",
    plate: "В456ГД150",
    type: "Газель",
    brand: "ГАЗ",
    model: "Next",
    year: 2022,
    capacity: 1500,
    volume: 12,
    length: 4.2,
    width: 2.0,
    height: 2.1,
    features: ["tent", "tail_lift"],
    driverId: "2",
    status: "in_use",
    mileage: 67000,
    insuranceExpiry: new Date(Date.now() + 86400000 * 120),
    inspectionExpiry: new Date(Date.now() + 86400000 * 200),
  },
  {
    id: "v3",
    plate: "Е789ЖЗ63",
    type: "Рефрижератор",
    brand: "Volvo",
    model: "FH 460",
    year: 2019,
    capacity: 10000,
    volume: 60,
    length: 9.5,
    width: 2.45,
    height: 2.5,
    features: ["refrigerator", "side_loading", "gps"],
    driverId: "3",
    status: "available",
    mileage: 312000,
    insuranceExpiry: new Date(Date.now() + 86400000 * 45),
    inspectionExpiry: new Date(Date.now() + 86400000 * 30),
  },
  {
    id: "v4",
    plate: "К012МН99",
    type: "Фура",
    brand: "Scania",
    model: "R450",
    year: 2021,
    capacity: 22000,
    volume: 100,
    length: 13.6,
    width: 2.45,
    height: 2.8,
    features: ["tent", "top_loading", "gps", "adr"],
    status: "maintenance",
    mileage: 189000,
    lastMaintenanceDate: new Date(),
    nextMaintenanceDate: new Date(Date.now() + 86400000 * 5),
  },
]

export const mockOrders: any[] = [
  {
    id: "1",
    source: "ATI.SU",
    routeFrom: "Москва",
    routeTo: "Санкт-Петербург",
    distance: 710,
    weight: 15000,
    volume: 82,
    cargoType: "Стройматериалы",
    loadingType: "pallets",
    requirements: "Тент, верхняя загрузка",
    price: 85000,
    priceNegotiable: false,
    payment: {
      type: "bank_transfer",
      vat: "with_vat",
      isPaid: false,
      dueDate: new Date(Date.now() + 86400000 * 14),
    },
    clientContact: "+7 (999) 123-45-67",
    clientName: "ООО СтройТорг",
    deadline: new Date(Date.now() + 86400000 * 2),
    status: "new",
    priority: "hot",
    aiScore: 95,
    aiReason: "Высокая маржинальность, короткий маршрут, проверенный клиент",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    source: "Груз.ру",
    routeFrom: "Казань",
    routeTo: "Нижний Новгород",
    distance: 395,
    weight: 8000,
    cargoType: "Оборудование",
    loadingType: "boxes",
    requirements: "Рефрижератор +5°C",
    price: null,
    priceNegotiable: true,
    payment: {
      type: "deferred",
      vat: "without_vat",
      deferredDays: 30,
      isPaid: false,
    },
    clientContact: "+7 (912) 555-33-22",
    clientName: "ИП Иванов",
    deadline: new Date(Date.now() + 86400000),
    status: "new",
    priority: "possible",
    aiScore: 72,
    aiReason: "Требуется уточнение цены, спецтранспорт",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    source: "Telegram",
    routeFrom: "Екатеринбург",
    routeTo: "Челябинск",
    distance: 210,
    weight: 3500,
    cargoType: "Продукты питания",
    loadingType: "pallets",
    requirements: "Санитарная книжка, мед. книжка",
    price: 28000,
    priceNegotiable: true,
    payment: {
      type: "cash",
      vat: "without_vat",
      isPaid: false,
    },
    clientContact: "+7 (343) 999-88-77",
    deadline: new Date(Date.now() + 86400000 * 3),
    status: "processing",
    priority: "possible",
    aiScore: 68,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    source: "ATI.SU",
    routeFrom: "Новосибирск",
    routeTo: "Омск",
    distance: 650,
    weight: 20000,
    volume: 96,
    cargoType: "Металлопрокат",
    loadingType: "bulk",
    price: 120000,
    priceNegotiable: false,
    payment: {
      type: "bank_transfer",
      vat: "with_vat",
      isPaid: false,
      dueDate: new Date(Date.now() + 86400000 * 7),
    },
    clientContact: "+7 (383) 444-55-66",
    clientName: "МеталлСервис",
    deadline: new Date(Date.now() + 86400000 * 4),
    status: "confirmed",
    priority: "hot",
    aiScore: 88,
    aiReason: "Крупный заказ, высокая прибыль",
    assignedDriver: "1",
    assignedVehicle: "v1",
    routeId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    source: "Объявления",
    routeFrom: "Ростов-на-Дону",
    routeTo: "Краснодар",
    distance: 275,
    weight: 5000,
    cargoType: "Мебель",
    loadingType: "boxes",
    requirements: "Грузчики 2 чел.",
    price: 35000,
    priceNegotiable: true,
    payment: {
      type: "cash",
      vat: "without_vat",
      isPaid: false,
    },
    clientContact: "+7 (863) 222-11-00",
    deadline: new Date(Date.now() + 86400000),
    status: "new",
    priority: "doubtful",
    aiScore: 45,
    aiReason: "Низкая маржа, требуются грузчики",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    source: "Груз.ру",
    routeFrom: "Воронеж",
    routeTo: "Липецк",
    distance: 120,
    weight: 2000,
    cargoType: "Запчасти",
    loadingType: "boxes",
    price: null,
    priceNegotiable: true,
    clientContact: "+7 (473) 111-22-33",
    deadline: new Date(Date.now() + 86400000 * 2),
    status: "new",
    priority: "needs_clarification",
    aiScore: 55,
    aiReason: "Нет информации о цене и условиях погрузки",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    source: "ATI.SU",
    routeFrom: "Новосибирск",
    routeTo: "Барнаул",
    distance: 230,
    weight: 3000,
    volume: 15,
    cargoType: "Электроника",
    loadingType: "boxes",
    requirements: "Бережная перевозка",
    price: 25000,
    priceNegotiable: true,
    payment: {
      type: "bank_transfer",
      vat: "with_vat",
      isPaid: false,
    },
    clientContact: "+7 (383) 777-88-99",
    clientName: "ТехноМир",
    deadline: new Date(Date.now() + 86400000 * 5),
    status: "new",
    priority: "possible",
    aiScore: 75,
    aiReason: "Подходит для догруза — направление совпадает с активным маршрутом",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockDrivers: any[] = [
  {
    id: "1",
    name: "Александр Петров",
    phone: "+7 (999) 111-22-33",
    vehicleId: "v1",
    vehicleType: "Фура 20т",
    vehiclePlate: "А123БВ777",
    currentLocation: "Москва",
    status: "available",
    ordersCompleted: 156,
    rating: 4.8,
    licenseNumber: "77 АА 123456",
    licenseExpiry: new Date(Date.now() + 86400000 * 365),
    medicalExpiry: new Date(Date.now() + 86400000 * 180),
    hiredAt: new Date(Date.now() - 86400000 * 730),
  },
  {
    id: "2",
    name: "Михаил Сидоров",
    phone: "+7 (999) 444-55-66",
    vehicleId: "v2",
    vehicleType: "Газель 1.5т",
    vehiclePlate: "В456ГД150",
    currentLocation: "Казань",
    status: "busy",
    ordersCompleted: 89,
    rating: 4.6,
    licenseNumber: "16 ВВ 654321",
    licenseExpiry: new Date(Date.now() + 86400000 * 500),
    hiredAt: new Date(Date.now() - 86400000 * 365),
  },
  {
    id: "3",
    name: "Дмитрий Козлов",
    phone: "+7 (999) 777-88-99",
    vehicleId: "v3",
    vehicleType: "Реф 10т",
    vehiclePlate: "Е789ЖЗ63",
    currentLocation: "Екатеринбург",
    status: "available",
    ordersCompleted: 234,
    rating: 4.9,
    licenseNumber: "66 СС 789012",
    licenseExpiry: new Date(Date.now() + 86400000 * 400),
    medicalExpiry: new Date(Date.now() + 86400000 * 90),
    hiredAt: new Date(Date.now() - 86400000 * 1095),
  },
]

export const mockStats: any = {
  totalOrders: 847,
  activeOrders: 23,
  completedToday: 12,
  revenue: 2450000,
  avgDeliveryTime: 18.5,
  vehicleUtilization: 78,
}

export const mockRoutes: any[] = [
  {
    id: "1",
    name: "Москва — СПб (оптимальный)",
    orders: ["1"],
    totalDistance: 710,
    estimatedTime: 9.5,
    fuelCost: 8520,
    tollCost: 1200,
    estimatedProfit: 75280,
    driver: mockDrivers[0],
    vehicleId: "v1",
    waypoints: [
      { name: "Москва", type: "start" },
      { name: "Тверь", type: "waypoint" },
      { name: "Санкт-Петербург", type: "end" },
    ],
    aiExplanation: "Прямой маршрут по М-11, минимум пробок. Оптимальное время выезда: 06:00",
    status: "planned",
  },
  {
    id: "2",
    name: "Объединённый: Казань — Н.Новгород",
    orders: ["2", "3"],
    totalDistance: 605,
    estimatedTime: 8,
    fuelCost: 7260,
    tollCost: 0,
    estimatedProfit: 48740,
    driver: mockDrivers[2],
    vehicleId: "v3",
    waypoints: [
      { name: "Казань", type: "start" },
      { name: "Нижний Новгород", type: "waypoint" },
      { name: "Екатеринбург", type: "end" },
    ],
    aiExplanation: "Комбинация 2 заказов в одну поездку. Экономия 15% на топливе.",
    status: "planned",
  },
  {
    id: "3",
    name: "Новосибирск — Омск",
    orders: ["4"],
    totalDistance: 650,
    estimatedTime: 8.5,
    fuelCost: 7800,
    tollCost: 500,
    estimatedProfit: 111700,
    driver: mockDrivers[0],
    vehicleId: "v1",
    waypoints: [
      { name: "Новосибирск", type: "start" },
      { name: "Омск", type: "end" },
    ],
    aiExplanation: "Крупный заказ, высокая маржинальность. Рекомендуется водитель с опытом перевозки металлопроката.",
    status: "active",
    startedAt: new Date(Date.now() - 86400000),
    photos: ["1", "2"],
  },
]

export const mockPhotos: any[] = [
  {
    id: "1",
    orderId: "4",
    routeId: "3",
    driverId: "1",
    type: "cargo_before",
    url: "/truck-cargo-loading-bay.jpg",
    uploadedBy: "1",
    uploadedAt: new Date(Date.now() - 86400000 * 2),
    syncStatus: "synced",
    aiClassification: {
      detectedType: "cargo_before",
      confidence: 0.95,
      description: "Фото кузова перед погрузкой. Кузов чистый, без повреждений.",
    },
  },
  {
    id: "2",
    orderId: "4",
    routeId: "3",
    driverId: "1",
    type: "cargo_after",
    url: "/loaded-truck-cargo.jpg",
    uploadedBy: "1",
    uploadedAt: new Date(Date.now() - 86400000),
    syncStatus: "synced",
    aiClassification: {
      detectedType: "cargo_after",
      confidence: 0.92,
      description: "Груз загружен, закреплён ремнями. Металлопрокат закреплён.",
      cargoFillPercent: 65, // Added fill percent
    },
  },
  {
    id: "3",
    orderId: "4",
    routeId: "3",
    driverId: "1",
    type: "receipt",
    url: "/fuel-gas-station-receipt.jpg",
    uploadedBy: "1",
    uploadedAt: new Date(Date.now() - 86400000),
    syncStatus: "synced",
    aiClassification: {
      detectedType: "receipt",
      confidence: 0.98,
      description: "Чек АЗС. Распознаны данные о заправке.",
    },
    ocrData: {
      amount: 4250,
      date: "2024-01-15",
      purpose: "Топливо ДТ",
      vendor: "Лукойл",
      rawText: "ЛУКОЙЛ АЗС №145\nДизель 85л x 50.00\nИТОГО: 4250.00",
    },
  },
  {
    id: "4",
    orderId: "4",
    routeId: "3",
    driverId: "3",
    type: "waybill",
    url: "/shipping-waybill-document.jpg",
    uploadedBy: "3",
    uploadedAt: new Date(),
    syncStatus: "synced",
    aiClassification: {
      detectedType: "waybill",
      confidence: 0.89,
      description: "Транспортная накладная. Распознан номер и маршрут.",
    },
    ocrData: {
      date: "2024-01-16",
      purpose: "ТТН №12345",
      rawText: "Транспортная накладная №12345\nОтправитель: МеталлСервис\nПолучатель: ...",
    },
  },
  {
    id: "5",
    orderId: "4",
    routeId: "3",
    driverId: "3",
    type: "damage",
    url: "/truck-cargo-damage-scratch.jpg",
    uploadedBy: "3",
    uploadedAt: new Date(),
    syncStatus: "synced",
    aiClassification: {
      detectedType: "damage",
      confidence: 0.85,
      description: "Обнаружена царапина на левом борту кузова. Рекомендуется зафиксировать в акте.",
    },
  },
]

export const mockChatMessages: any[] = [
  {
    id: "m1",
    senderId: "1",
    senderRole: "driver",
    senderName: "Александр Петров",
    routeId: "3",
    content: "Загрузился, выезжаю из Новосибирска",
    type: "text",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: "m2",
    senderId: "u1",
    senderRole: "logist",
    senderName: "Иван Логистов",
    recipientId: "1",
    routeId: "3",
    content: "Принял. Следи за временем, клиент ждёт до 18:00",
    type: "text",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 + 3600000),
  },
  {
    id: "m3",
    senderId: "1",
    senderRole: "driver",
    senderName: "Александр Петров",
    routeId: "3",
    content: "Пробка на выезде, задержка ~30 мин",
    type: "alert",
    isRead: false,
    createdAt: new Date(Date.now() - 3600000),
  },
]

export const mockDogrizSuggestions: any[] = [
  {
    id: "d1",
    routeId: "3",
    vehicleId: "v1",
    suggestedOrderId: "7",
    currentFillPercent: 65,
    availableCapacity: 7000, // kg available
    suggestedOrder: mockOrders.find((o: any) => o.id === "7")!,
    aiReason:
      "Маршрут Новосибирск-Омск проходит через направление на Барнаул. Кузов загружен на 65%, свободно 7т. Заказ на 3т электроники идеально вписывается. Дополнительный доход: 25 000 руб.",
    status: "pending",
    createdAt: new Date(),
  },
]